# Generated by Django 4.2.21 on 2025-08-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_car_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created',
        ),
    ]
