# Generated by Django 4.2.15 on 2024-08-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
